name: Build

on:
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
      - name: Node.js環境のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./pages/package-lock.json
      - name: 依存関係のインストール
        run: npm install
        working-directory: ./pages/
      - name: Viteのプロジェクトのビルド
        run: npm run build
        working-directory: ./pages/

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Transfer Build Artifacts (rsync)
        uses: sftp-upload/action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./pages/dist
          target: '/var/docker/link/pages/dist'

      
