name: Build

on:
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
      - name: Node.js環境のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./pages/package-lock.json
      - name: 依存関係のインストール
        run: npm install
        working-directory: ./pages/
      - name: Viteのプロジェクトのビルド
        run: npm run build
        working-directory: ./pages/

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --delete
          path: ${{ secrets.VPS_LINK_SOURCE}}
          remote_path: ${{ secrets.VPS_LINK_TARGET}}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY}}